# Generated by Django 3.1.5 on 2021-01-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=30)),
                ('releasedate', models.DateField()),
                ('actor', models.CharField(max_length=30)),
                ('actress', models.CharField(max_length=30)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
